services:
  db:
    image: postgres:15
    container_name: airflow-tutorial-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=food_delivery_db
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d